### ISSUE TITLE
Rtools40 is not recognised on the win10

### ISSUE THREAD

**Issue by kongdd** [r-windows/rtools-installer#10]
I am using R4.0.0 and rtools40. When I am trying to build my package, R can't find rtools40.

```r
devtools::load_all()
#> WARNING: Rtools is required to build R packages, but the version of Rtools previously inst
#> alled in C:/rtools40 has been deleted
```

``` r
pkgbuild::find_rtools(TRUE)
#> Scanning R CMD config CC...
#> cc_path:  
#> '' does not exist
#> Scanning path...
#> ls: C:\PROGRA~1\Git\usr\bin\ls.exe 
#> gcc_path: c:\rtools40\mingw64\bin\gcc.exe 
#> Scanning registry...
#> Found C:/rtools40 for 4.0
#> WARNING: Rtools is required to build R packages, but the version of Rtools previously installed in C:/rtools40 has been deleted.
#> 
#> Please download and install Rtools custom from http://cran.r-project.org/bin/windows/Rtools/.
```

**Comment by jeroen** [comment]
Did you follow the instructions on the [rtools40 page](https://cran.r-project.org/bin/windows/Rtools/) under __*Putting Rtools on the PATH*__ ?

There are also a few bugs in the `pkgbuild` package. We will release a new version to cran very soon.

**Comment by kongdd** [comment]
fixed. It turns out that rtools40 has conflicts with `C:\Program Files\Git\usr\bin\`. 
`c:\rtools40\usr\bin` should be in the first in the PATH.
