### ISSUE TITLE
C:/rtools40/usr/mingw_32/bin/gcc: No such file or directory

### ISSUE THREAD

**Issue by vidarsumo** [r-windows/rtools-installer#19]
I installed rtools40 on Windows 10 (rtools40v2-x86_64.exe) after installation I created a text file .Renviron, `usethis::edit_r_environ()`, and added this line PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"

When I run Sys.which("make") I'll get: "C:\\rtools40\\usr\\bin\\make.exe"

However, when trying to install an R package from source I get an error:
```
install.packages("jsonlite", type = "source")
C:/rtools40/usr/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-4.1.0/include" -DNDEBUG -Iyajl/api       -D__USE_MINGW_ANSI_STDIO   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c base64.c -o base64.o
sh: line 1: C:/rtools40/usr/mingw_32/bin/gcc: No such file or directory
make: *** [C:/PROGRA~1/R/R-4.1.0/etc/i386/Makeconf:238: base64.o] Error 127
ERROR: compilation failed for package 'jsonlite'
* removing 'C:/Users/vidar/Documents/R/win-library/4.1/jsonlite'
* restoring previous 'C:/Users/vidar/Documents/R/win-library/4.1/jsonlite'
Warning in install.packages :
  installation of package ‘jsonlite’ had non-zero exit status

```

**Comment by jeroen** [comment]
The path to gcc is wrong, do you have an ennvar `BINPREF` set? You should remove/unset that.

**Comment by vidarsumo** [comment]
I assume you're talking about the .Renviron file. I do not have `BINPREF` there. Only `PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"`

**Comment by jeroen** [comment]
What do you see if you run `Sys.getenv("BINPREF")` in R?

**Comment by vidarsumo** [comment]
"C:/rtools40/usr/mingw_$(WIN)/bin/"

**Comment by jeroen** [comment]
OK so that is the problem. Somewhere you have set a configuration to set this variable, and you should not do that. Please check your local settings, and remove this.

**Comment by vidarsumo** [comment]
For some reason I have set this in .Rprofile, don't know why. Removing this solved the issue. Thank you so much jeroen.
