### ISSUE TITLE
Rtools4 and log4j vulnerabilities?

### ISSUE THREAD

**Issue by jhollist** [r-windows/rtools-installer#21]
I am completely out of my element with this question, but I've been pinged at work (because I'm often "the R guy" there) about log4j vulnerabilities and Rtools4.  From what I can see it doesn't look like this is an issue as there I don't see any Java in Rtools4.  Just wondering if you could confirm this, point me to something I could use to test for myself, or point me to a better place to ask.

Thanks and apologies!

**Comment by jhollist** [comment]
@hrbrmstr to the rescue!  https://twitter.com/hrbrmstr/status/1481286247607844868  Will close this.

**Comment by jeroen** [comment]
Indeed there is no Java in R or rtools.
