### ISSUE TITLE
RStudio not recognising R tools

### ISSUE THREAD

**Issue by adamrobinson361** [r-windows/rtools-installer#4]
Following on from my previous issue it looks like installing from source is working well for a number of packages. 

Unfortunately when I switch to using packrat it prompts me to install r tools (35) even though 40 is installed and setup with paths environment varialbes etc. Is there a way to override this so that packrat can use rtools40?

Regards,

Adam

**Comment by adamrobinson361** [comment]
Narrowed this down to the Makeconf files. In the makeconf the mingw folders were referred to as mingw_$(WIN) whereas the structure in 40 is mingw$(WIN) without the underscore. Not sure if this is from the rtools installer or a previous installation I've had. Was surprised that this override the R home .Rprofile though.

**Comment by jeroen** [comment]
Are you using the `R-testing-win.exe` build that is provided on the [rtools40 homepage](https://cran.r-project.org/bin/windows/testing/rtools40.html)? You cannot mix and match R 3.5 with rtools 40.

**Comment by adamrobinson361** [comment]
I've been using with 3.5.1 which after the changes above works well apart from the particular packages listed on other issues. Sounds like I might be getting a bit ahead of the testing phase though.

Will leave this issue now as conscious I'm spamming a bit.
