### ISSUE TITLE
Sophos anti-virus detects mal/encpk-anx

### ISSUE THREAD

**Issue by samclifford** [r-windows/rtools-installer#6]
My work anti-virus is convinced that the mingw32 folder that gets created contains 6 threats:

* `bin\gcov.exe`
* `bin\gcov-tool.exe`
* `lib\gcc\....\collect2.exe`
* `lib\gcc\....\lto-wrapperexe`
* `bin\elfedit.exe`
* `bin\dllwrap.exe`

Windows 10.0, Sophos 2.3.0 endpoint advanced 10.8.3.441

**Comment by jeroen** [comment]
Probably https://github.com/msys2/MINGW-packages/issues/4085 Uwe reports the same on WinBuilder.

I think it is very likely this is a false positive (viruses probably use the same toolchain).

**Comment by jeroen** [comment]
Uwe reports the same on WinBuilder.
